GET localhost:8081/
###
GET localhost:8081/health_check
###
POST http://localhost:8081/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}
###
POST http://localhost:8081/register
Content-Type: application/json

{
  "username": "a",
  "password": "a",
  "api_key": "db0fe35b-0d88-4d03-a774-12fbae54aa51"
}
###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}
###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}
###
GET http://localhost:8081/api/email_threads/1/current_ranking
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###