# Dockerfile-ssh-proxy
FROM alpine:latest

# Installiere benötigte Pakete einschließlich curl
RUN apk update && apk add --no-cache autossh openssh curl

# SSH-Schlüssel und Startskript kopieren
COPY /docker/ssh_proxy/id_rsa /root/.ssh/id_rsa
COPY /docker/ssh_proxy/start_ssh_proxy.sh /scripts/start_ssh_proxy.sh

# Berechtigungen setzen
RUN chmod 600 /root/.ssh/id_rsa && chmod +x /scripts/start_ssh_proxy.sh

# Führe das Startskript aus
CMD ["/scripts/start_ssh_proxy.sh"]