GET localhost:8081/api/email_threads/rankings
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###
GET localhost:8081/api/email_threads/ratings
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###
GET localhost:8081/api/email_threads/rankings/1
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###
GET localhost:8081/api/email_threads/ratings/4
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###
GET localhost:8081/api/email_threads/ratings/4/41
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
####
GET localhost:8081/api/feature_type_mapping
###
GET localhost:8081/api/feature_type_mapping/1
###
GET localhost:8081/api/feature_type_mapping/abstract_summary
###
GET localhost:8081/api/get_rating/4/41
Authorization: db0fe35b-0d88-4d03-a774-12fbae54aa51
###