services:
  nginx-service:
    container_name: llars_nginx_service
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - backend-flask-service
      - frontend-vue-service
    environment:
      - TZ=Europe/Berlin

  backend-flask-service:
    container_name: llars_flask_service
    build:
      context: .
      dockerfile: docker/flask/Dockerfile-flask
    expose:
      - "8081"
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=/app/main.py
    depends_on:
      db-maria-service:
        condition: service_healthy


  frontend-vue-service:
    container_name: llars_frontend_service
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/vue/Dockerfile-vue
    expose:
      - "5173"
    environment:
      - TZ=Europe/Berlin
    develop:
      watch:
        - action: sync
          path: ./llars-frontend/src
          target: /vue/src
          ignore:
            - node_modules/

  backend-supervisor-service:
    container_name: llars_supervisor_service
    build:
      context: .
      dockerfile: docker/supervisor/Dockerfile-supervisor
    command: [ "/supervisor/start_supervisor.sh" ]
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - backend-flask-service
      - db-maria-service
      - frontend-vue-service

  db-maria-service:
    container_name: llars_db_service
    build:
      context: .
      dockerfile: docker/db/Dockerfile-mariadb
    env_file:
      - .env
    ports:
      - "3310:3306"
    volumes:
      - llarsdb:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  ssh-proxy-service:
    container_name: kia_docker_ssh_proxy_service
    profiles:
      - backend
    build:
      context: .
      dockerfile: docker/ssh_proxy/Dockerfile-ssh-proxy
    ports:
      - "8093:8093"
    environment:
      - PROXY_REMOTE_USER=${PROXY_REMOTE_USER}
      - PROXY_REMOTE_HOST=${PROXY_REMOTE_HOST}
      - PROXY_REMOTE_PORT=${PROXY_REMOTE_PORT}
      - PROXY_LOCAL_PORT=${PROXY_LOCAL_PORT}
    command: [ "/scripts/start_ssh_proxy.sh" ]


volumes:
  llarsdb: