"""
LaTeX Collab Seeder

Creates a demo LLARS paper workspace with full ACL-style structure in development setups.
Idempotent: will not create duplicates on repeated startups.
"""

from datetime import datetime


# =============================================================================
# PAPER CONTENT
# =============================================================================

MAIN_TEX = r"""% LLARS: LLM Assisted Research System
% Paper for ACL/EMNLP/LREC-COLING 2025

\documentclass[11pt]{article}
\usepackage[hyperref]{acl2023}
\usepackage{times}
\usepackage{latexsym}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{xcolor}
\usepackage{subcaption}
\usepackage{tikz}
\usetikzlibrary{shapes.geometric, arrows, positioning, fit, backgrounds}

\title{LLARS: A Collaborative Platform for LLM-Assisted Research with Human-in-the-Loop Evaluation}

\author{
  Philipp Steigerwald \\
  Technische Hochschule N\"urnberg \\
  \texttt{philipp.steigerwald@th-nuernberg.de}
}

\begin{document}
\maketitle

\input{sections/abstract}
\input{sections/introduction}
\input{sections/related_work}
\input{sections/architecture}
\input{sections/features}
\input{sections/evaluation}
\input{sections/conclusion}

\bibliographystyle{plainnat}
\bibliography{references}

\end{document}
"""

ABSTRACT_TEX = r"""\begin{abstract}
We present LLARS (LLM Assisted Research System), an open-source platform designed for collaborative evaluation of Large Language Model outputs in research contexts.
LLARS addresses the critical need for systematic human evaluation of LLM-generated content by providing an integrated environment that combines (1) flexible rating and ranking interfaces for comparative assessment, (2) an LLM-as-Judge module for automated pairwise comparisons, (3) a RAG-enhanced document pipeline with web crawling capabilities, and (4) real-time multi-user collaboration features.
The system implements role-based access control, supports multiple evaluation methodologies, and provides comprehensive analytics for inter-annotator agreement.
We describe the system architecture, key features, and demonstrate its application in evaluating counseling email responses generated by different LLMs.
LLARS is available as open-source software and has been deployed in academic research settings.
\end{abstract}
"""

INTRODUCTION_TEX = r"""\section{Introduction}

The rapid advancement of Large Language Models (LLMs) has created an urgent need for robust evaluation frameworks that can assess the quality of generated text across diverse dimensions \cite{chang2024survey}.
While automatic metrics provide scalable assessment, human evaluation remains essential for capturing nuanced aspects of text quality such as helpfulness, appropriateness, and factual accuracy \cite{clark2021all}.

Current approaches to human evaluation of LLMs face several challenges:

\begin{enumerate}
    \item \textbf{Scalability}: Coordinating multiple annotators across distributed teams is logistically complex.
    \item \textbf{Consistency}: Ensuring comparable evaluation standards across annotators requires careful interface design.
    \item \textbf{Integration}: Combining human judgments with automated metrics and LLM-based evaluation is technically demanding.
    \item \textbf{Documentation}: Tracking evaluation provenance and maintaining reproducibility is often neglected.
\end{enumerate}

To address these challenges, we introduce LLARS (LLM Assisted Research System), a comprehensive platform that provides:

\begin{itemize}
    \item \textbf{Flexible Evaluation Interfaces}: Support for both rating (absolute scores) and ranking (comparative ordering) paradigms
    \item \textbf{LLM-as-Judge Integration}: Automated pairwise comparison using configurable LLM evaluators
    \item \textbf{RAG Pipeline}: Document ingestion with semantic search for grounded evaluation
    \item \textbf{Real-time Collaboration}: Multi-user editing with conflict resolution via CRDTs
    \item \textbf{Comprehensive Access Control}: Role-based permissions for research team management
\end{itemize}

The following sections describe the system architecture and key features in detail.
"""

RELATED_WORK_TEX = r"""\section{Related Work}

\paragraph{Human Evaluation Platforms}
Several platforms have been developed for collecting human judgments on NLP systems.
Amazon Mechanical Turk \cite{crowston2012amazon} provides a general crowdsourcing infrastructure but lacks domain-specific features for NLP evaluation.
Potato \cite{pei2022potato} offers annotation interfaces but focuses primarily on labeling tasks rather than comparative evaluation.
Label Studio provides flexible annotation capabilities but requires significant customization for LLM evaluation workflows.

\paragraph{LLM Evaluation Frameworks}
Recent work has explored using LLMs themselves as evaluators \cite{zheng2023judging}.
Chatbot Arena \cite{chiang2024chatbot} implements pairwise comparison at scale but operates as a public benchmark rather than a customizable research tool.
MT-Bench \cite{zheng2023judging} provides standardized benchmarks but limited support for custom evaluation criteria.

\paragraph{Retrieval-Augmented Generation}
RAG systems \cite{lewis2020retrieval} have become essential for grounding LLM outputs in factual sources.
While frameworks like LangChain and LlamaIndex provide RAG capabilities, they require substantial integration effort for evaluation workflows.

LLARS distinguishes itself by providing an integrated platform that combines human evaluation, LLM-as-Judge, and RAG capabilities in a single collaborative environment designed specifically for research contexts.
"""

ARCHITECTURE_TEX = r"""\section{System Architecture}

LLARS follows a modern microservices architecture deployed via Docker Compose, ensuring reproducibility and ease of deployment.

\subsection{Backend Services}

The backend is implemented in Python using Flask 3.0, providing RESTful APIs for all system functionality.
Key components include:

\begin{itemize}
    \item \textbf{Authentication}: Integration with Authentik for OAuth2/OIDC-based single sign-on
    \item \textbf{Database}: MariaDB 11.2 for relational data with SQLAlchemy ORM
    \item \textbf{Vector Store}: ChromaDB for embedding storage and semantic search
    \item \textbf{Real-time Communication}: Socket.IO for live updates and collaboration
    \item \textbf{Task Queue}: Background processing for embedding generation and web crawling
\end{itemize}

\subsection{Frontend Application}

The frontend is built with Vue.js 3.4 and Vuetify 3.5, providing a responsive single-page application.
Real-time collaboration is implemented using Yjs \cite{nicolaescu2016yjs}, a CRDT-based framework that enables conflict-free concurrent editing.

\subsection{RAG Pipeline}

The RAG pipeline supports multiple document formats (PDF, HTML, Markdown) and includes:

\begin{itemize}
    \item \textbf{Web Crawler}: Playwright-based crawler with screenshot capture for visual content
    \item \textbf{Embedding Models}: Support for both local (sentence-transformers) and API-based (LiteLLM) embedding models
    \item \textbf{Hybrid Search}: Combined semantic and lexical (BM25) retrieval with reciprocal rank fusion
\end{itemize}

\begin{figure}[t]
\centering
\begin{tikzpicture}[
    node distance=0.8cm,
    box/.style={rectangle, draw, rounded corners, minimum width=2.2cm, minimum height=0.7cm, font=\small},
    bigbox/.style={rectangle, draw, dashed, rounded corners, inner sep=0.3cm},
]
    % Frontend
    \node[box, fill=blue!20] (frontend) {Vue.js Frontend};

    % Backend
    \node[box, fill=green!20, below=of frontend] (flask) {Flask API};
    \node[box, fill=green!20, right=0.5cm of flask] (socketio) {Socket.IO};

    % Storage
    \node[box, fill=orange!20, below left=0.8cm and -0.5cm of flask] (mariadb) {MariaDB};
    \node[box, fill=orange!20, below right=0.8cm and -0.5cm of flask] (chromadb) {ChromaDB};

    % External
    \node[box, fill=purple!20, right=1.5cm of socketio] (llm) {LLM API};
    \node[box, fill=gray!20, below=of llm] (auth) {Authentik};

    % Arrows
    \draw[->] (frontend) -- (flask);
    \draw[->] (frontend) -- (socketio);
    \draw[->] (flask) -- (mariadb);
    \draw[->] (flask) -- (chromadb);
    \draw[->] (flask) -- (llm);
    \draw[->] (flask) -- (auth);
\end{tikzpicture}
\caption{LLARS system architecture overview.}
\label{fig:architecture}
\end{figure}
"""

FEATURES_TEX = r"""\section{Key Features}

\subsection{Rating and Ranking Evaluation}

LLARS supports two primary evaluation paradigms:

\paragraph{Rating Mode}
Annotators assign absolute scores to individual items using configurable scales.
The interface presents LLM-generated features (e.g., summaries, extracted information) alongside source material, allowing annotators to assess quality dimensions such as accuracy, completeness, and relevance.

\paragraph{Ranking Mode}
Annotators order multiple items by preference using drag-and-drop interaction.
This comparative approach is particularly effective for assessing relative quality when absolute standards are difficult to define.

Both modes support configurable evaluation scenarios with:
\begin{itemize}
    \item Time-bounded evaluation periods
    \item Flexible annotator assignment (all items vs. round-robin distribution)
    \item Randomized presentation order to minimize bias
    \item Progress tracking and completion monitoring
\end{itemize}

\subsection{LLM-as-Judge Module}

The LLM-as-Judge module implements automated pairwise comparison following established protocols \cite{zheng2023judging}.
Key features include:

\begin{itemize}
    \item \textbf{Configurable Evaluation Criteria}: Custom rubrics defined through an administrative interface
    \item \textbf{Position Bias Mitigation}: Automatic swapping of response positions with result aggregation
    \item \textbf{Multi-Model Support}: Integration with various LLM providers via LiteLLM
    \item \textbf{Session Management}: Batch processing with pause/resume capability
    \item \textbf{Result Analytics}: Visualization of win rates, tie frequencies, and confidence distributions
\end{itemize}

\subsection{Collaborative Document Editing}

LLARS includes a LaTeX/Markdown editor with real-time collaboration:

\begin{itemize}
    \item \textbf{Multi-user Editing}: Concurrent editing with live cursor positions and user presence indicators
    \item \textbf{Version History}: Git-like versioning with diff visualization
    \item \textbf{PDF Compilation}: Integrated LaTeX compilation with live preview
    \item \textbf{AI Writing Assistant}: Ghost text completion, rewriting suggestions, and citation finding via RAG
\end{itemize}

\subsection{Access Control and Analytics}

The system implements comprehensive role-based access control (RBAC):

\begin{itemize}
    \item \textbf{Roles}: Admin, Researcher, Viewer, Chatbot Manager with granular permissions
    \item \textbf{Sharing}: Document and collection sharing with user/role-based access lists
    \item \textbf{Analytics}: Integrated Matomo tracking for usage analytics and research metrics
\end{itemize}
"""

EVALUATION_TEX = r"""\section{Use Case: Counseling Email Evaluation}

We deployed LLARS to evaluate LLM-generated responses in an online counseling context.
The evaluation involved:

\paragraph{Dataset}
Email threads from an online counseling service (anonymized), with responses generated by GPT-4, Claude-3, and Mistral-7B.

\paragraph{Evaluation Design}
\begin{itemize}
    \item 5 trained annotators (psychology students)
    \item Rating of 4 quality dimensions per response
    \item Ranking of responses within each thread
    \item LLM-as-Judge comparison for all response pairs
\end{itemize}

\paragraph{Results}
The platform enabled collection of 2,400 ratings and 600 rankings over a 4-week period.
Inter-annotator agreement (Krippendorff's $\alpha$) ranged from 0.61 to 0.78 across dimensions.
LLM-as-Judge results showed moderate correlation ($r = 0.54$) with human rankings, with systematic differences in empathy assessment.

Table~\ref{tab:results} summarizes the evaluation results.

\begin{table}[t]
\centering
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Accuracy} & \textbf{Empathy} & \textbf{Helpful} & \textbf{Overall} \\
\midrule
GPT-4 & 4.2 & 3.8 & 4.1 & 4.0 \\
Claude-3 & 4.0 & \textbf{4.2} & 4.0 & 4.1 \\
Mistral-7B & 3.5 & 3.2 & 3.4 & 3.4 \\
\bottomrule
\end{tabular}
\caption{Mean ratings (1-5 scale) for counseling response quality across three LLMs.}
\label{tab:results}
\end{table}

\subsection{Technical Requirements}

LLARS is designed for deployment on standard server infrastructure:

\begin{table}[h]
\centering
\begin{tabular}{ll}
\toprule
\textbf{Component} & \textbf{Requirement} \\
\midrule
CPU & 4+ cores \\
RAM & 16GB minimum \\
Storage & 50GB+ SSD \\
Docker & 20.10+ \\
\bottomrule
\end{tabular}
\caption{Minimum system requirements}
\label{tab:requirements}
\end{table}

The system supports both CPU-only and GPU-accelerated configurations for local embedding models.
"""

CONCLUSION_TEX = r"""\section{Conclusion}

LLARS provides a comprehensive platform for LLM evaluation research, combining human annotation interfaces, automated LLM-as-Judge capabilities, and RAG-enhanced document management in a collaborative environment.
The system addresses practical challenges in coordinating multi-annotator evaluation studies while maintaining flexibility for diverse research designs.

Future work will focus on:
\begin{enumerate}
    \item Enhanced inter-annotator agreement analytics
    \item Active learning for efficient annotation
    \item Integration with additional LLM evaluation benchmarks
\end{enumerate}

LLARS is available as open-source software at \url{https://github.com/llars-project/llars}.

\section*{Limitations}

The current system has several limitations:
\begin{enumerate}
    \item The LLM-as-Judge module requires API access to commercial LLMs for optimal performance.
    \item Real-time collaboration features require stable network connectivity.
    \item The system has been primarily tested with German-language content.
\end{enumerate}

\section*{Ethics Statement}

LLARS includes built-in anonymization tools for processing sensitive data.
All evaluation studies conducted with the platform followed institutional ethics guidelines.
The counseling email dataset used in our case study was collected with informed consent and IRB approval.
"""

REFERENCES_BIB = r"""@article{chang2024survey,
  title={A Survey on Evaluation of Large Language Models},
  author={Chang, Yupeng and Wang, Xu and Wang, Jindong and Wu, Yuan and Yang, Linyi and Zhu, Kaijie and Chen, Hao and Yi, Xiaoyuan and Wang, Cunxiang and Wang, Yidong and others},
  journal={ACM Transactions on Intelligent Systems and Technology},
  volume={15},
  number={3},
  pages={1--45},
  year={2024},
  publisher={ACM}
}

@inproceedings{clark2021all,
  title={All That's 'Human' Is Not Gold: Evaluating Human Evaluation of Generated Text},
  author={Clark, Elizabeth and August, Tal and Serber, Sofia and Haduong, Nithum and Gururangan, Suchin and Smith, Noah A},
  booktitle={Proceedings of the 59th Annual Meeting of the Association for Computational Linguistics},
  pages={7282--7296},
  year={2021}
}

@inproceedings{crowston2012amazon,
  title={Amazon Mechanical Turk: A research tool for organizations and information systems scholars},
  author={Crowston, Kevin},
  booktitle={Shaping the Future of ICT Research. Methods and Approaches},
  pages={210--221},
  year={2012},
  publisher={Springer}
}

@inproceedings{pei2022potato,
  title={Potato: The Portable Text Annotation Tool},
  author={Pei, Jiaxin and Anand, Aparna and Jurgens, David},
  booktitle={Proceedings of the 2022 Conference on Empirical Methods in Natural Language Processing: System Demonstrations},
  pages={327--337},
  year={2022}
}

@article{zheng2023judging,
  title={Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena},
  author={Zheng, Lianmin and Chiang, Wei-Lin and Sheng, Ying and Zhuang, Siyuan and Wu, Zhanghao and Zhuang, Yonghao and Lin, Zi and Li, Zhuohan and Li, Dacheng and Xing, Eric P and others},
  journal={arXiv preprint arXiv:2306.05685},
  year={2023}
}

@article{chiang2024chatbot,
  title={Chatbot Arena: An Open Platform for Evaluating LLMs by Human Preference},
  author={Chiang, Wei-Lin and Zheng, Lianmin and Sheng, Ying and Angelopoulos, Anastasios Nikolas and Li, Tianle and Li, Dacheng and Zhang, Hao and Zhu, Banghua and Jordan, Michael and Gonzalez, Joseph E and others},
  journal={arXiv preprint arXiv:2403.04132},
  year={2024}
}

@article{lewis2020retrieval,
  title={Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks},
  author={Lewis, Patrick and Perez, Ethan and Piktus, Aleksandra and Petroni, Fabio and Karpukhin, Vladimir and Goyal, Naman and K{\"u}ttler, Heinrich and Lewis, Mike and Yih, Wen-tau and Rockt{\"a}schel, Tim and others},
  journal={Advances in Neural Information Processing Systems},
  volume={33},
  pages={9459--9474},
  year={2020}
}

@inproceedings{nicolaescu2016yjs,
  title={Yjs: A Framework for Near Real-Time P2P Shared Editing on Arbitrary Data Types},
  author={Nicolaescu, Petru and Jahns, Kevin and Derntl, Michael and Klamma, Ralf},
  booktitle={Engineering the Web in the Big Data Era},
  pages={675--678},
  year={2016},
  publisher={Springer}
}
"""

ACL_STYLE = r"""% ACL 2023 style file (simplified version for demo)
% This is a minimal style - in production use the official acl2023.sty

\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{acl2023}[2023/01/01 ACL 2023 Style]

\RequirePackage{natbib}
\RequirePackage{url}
\RequirePackage{hyperref}
\RequirePackage{geometry}
\RequirePackage{fancyhdr}
\RequirePackage{enumitem}

\geometry{
  a4paper,
  top=2.5cm,
  bottom=2.5cm,
  left=2.5cm,
  right=2.5cm
}

\setlength{\parindent}{1em}
\setlength{\parskip}{0.3em}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0pt}

% Abstract environment
\renewenvironment{abstract}{%
  \begin{center}
    \textbf{Abstract}
  \end{center}
  \begin{quote}
    \small
}{%
  \end{quote}
}

\DeclareOption{hyperref}{\PassOptionsToPackage{colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue}{hyperref}}
\ProcessOptions\relax
"""


def initialize_latex_collab_defaults(db):
    """Initialize LaTeX Collab demo workspace with LLARS paper."""
    from ..models import (
        LatexWorkspace, LatexDocument, LatexNodeType, LatexWorkspaceVisibility, LatexCommit
    )

    # Check if demo workspace already exists
    existing = LatexWorkspace.query.filter_by(name='LLARS Paper 2025').first()
    if existing:
        return

    # Create workspace
    workspace = LatexWorkspace(
        name='LLARS Paper 2025',
        owner_username='admin',
        visibility=LatexWorkspaceVisibility.private,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.session.add(workspace)
    db.session.flush()

    # Create folder structure
    sections_folder = LatexDocument(
        workspace_id=workspace.id,
        parent_id=None,
        node_type=LatexNodeType.folder,
        title='sections',
        order_index=0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    figures_folder = LatexDocument(
        workspace_id=workspace.id,
        parent_id=None,
        node_type=LatexNodeType.folder,
        title='figures',
        order_index=1,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.session.add(sections_folder)
    db.session.add(figures_folder)
    db.session.flush()

    # Create main.tex
    main_doc = LatexDocument(
        workspace_id=workspace.id,
        parent_id=None,
        node_type=LatexNodeType.file,
        title='main.tex',
        order_index=2,
        content_text=MAIN_TEX,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.session.add(main_doc)
    db.session.flush()
    main_doc.yjs_doc_id = f"latex_{main_doc.id}"

    # Create references.bib
    refs_doc = LatexDocument(
        workspace_id=workspace.id,
        parent_id=None,
        node_type=LatexNodeType.file,
        title='references.bib',
        order_index=3,
        content_text=REFERENCES_BIB,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.session.add(refs_doc)
    db.session.flush()
    refs_doc.yjs_doc_id = f"latex_{refs_doc.id}"

    # Create acl2023.sty
    style_doc = LatexDocument(
        workspace_id=workspace.id,
        parent_id=None,
        node_type=LatexNodeType.file,
        title='acl2023.sty',
        order_index=4,
        content_text=ACL_STYLE,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.session.add(style_doc)
    db.session.flush()
    style_doc.yjs_doc_id = f"latex_{style_doc.id}"

    # Create section files
    section_files = [
        ('abstract.tex', ABSTRACT_TEX, 0),
        ('introduction.tex', INTRODUCTION_TEX, 1),
        ('related_work.tex', RELATED_WORK_TEX, 2),
        ('architecture.tex', ARCHITECTURE_TEX, 3),
        ('features.tex', FEATURES_TEX, 4),
        ('evaluation.tex', EVALUATION_TEX, 5),
        ('conclusion.tex', CONCLUSION_TEX, 6),
    ]

    for filename, content, order in section_files:
        doc = LatexDocument(
            workspace_id=workspace.id,
            parent_id=sections_folder.id,
            node_type=LatexNodeType.file,
            title=filename,
            order_index=order,
            content_text=content,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )
        db.session.add(doc)
        db.session.flush()
        doc.yjs_doc_id = f"latex_{doc.id}"

    # Set main document
    workspace.main_document_id = main_doc.id

    db.session.commit()

    # Create initial commit with all files
    all_docs = LatexDocument.query.filter_by(workspace_id=workspace.id).all()
    docs_by_id = {d.id: d for d in all_docs}

    def get_doc_path(doc_id, cache=None):
        """Build file path from document hierarchy."""
        if cache is None:
            cache = {}
        if doc_id in cache:
            return cache[doc_id]
        doc = docs_by_id.get(doc_id)
        if not doc:
            return ""
        if doc.parent_id is None:
            path = doc.title
        else:
            parent_path = get_doc_path(doc.parent_id, cache)
            path = f"{parent_path}/{doc.title}" if parent_path else doc.title
        cache[doc_id] = path
        return path

    path_cache = {}
    nodes = []
    for doc in all_docs:
        node_type = doc.node_type.value if hasattr(doc.node_type, "value") else str(doc.node_type)
        nodes.append({
            "id": doc.id,
            "path": get_doc_path(doc.id, path_cache),
            "title": doc.title,
            "node_type": node_type,
            "asset_id": doc.asset_id,
            "content_text": doc.content_text,
        })

    workspace_snapshot = {
        "workspace_id": workspace.id,
        "main_document_id": workspace.main_document_id,
        "nodes": nodes,
        "created_at": datetime.utcnow().isoformat(),
    }

    # Create a single init commit for the workspace (not document-specific)
    init_commit = LatexCommit(
        workspace_id=workspace.id,
        document_id=main_doc.id,  # Reference main.tex as primary document
        author_username='admin',
        message='Initial commit: LLARS Paper 2025',
        diff_summary={"files_added": len([n for n in nodes if n["node_type"] == "file"])},
        content_snapshot=main_doc.content_text,
        workspace_snapshot=workspace_snapshot,
        created_at=datetime.utcnow(),
    )
    db.session.add(init_commit)
    db.session.commit()

    print(f"[LaTeX Collab] Created LLARS Paper 2025 workspace (id={workspace.id}) with initial commit")
