# docker/nginx/Dockerfile-nginx
FROM nginx:alpine

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/50x/50x.html /usr/share/nginx/html/50x.html
COPY docker/nginx/50x/50x.css /usr/share/nginx/html/50x.css
COPY docker/nginx/50x/50x.js /usr/share/nginx/html/50x.js
COPY docker/nginx/50x/assets /usr/share/nginx/html/assets
