GET http://localhost:8081/
###
GET http://localhost:8081/health_check
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "a",
  "password": "a",
  "api_key": "db0fe35b-0d88-4d03-a774-12fbae54aa51"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "demo_mr",
  "password": "kia_demo_mr"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "demo_jb",
  "password": "kia_demo_jb"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "bke_dana",
  "password": "micivionterm"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "bke_maria",
  "password": "cernistinsto"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "tester2",
  "password": "llars_tester2"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "tester3",
  "password": "llars_tester3"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "api_key": "0b09e690-365b-4a55-b9b3-04c0614f773a"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "ieb_vanessa",
  "password": "toralvamplech"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "ieb_franziska",
  "password": "kirchmasoosphie"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST https://llars.e-beratungsinstitut.de/api/register
Content-Type: application/json

{
  "username": "ieb_michelle",
  "password": "ikasicherllea"
}