GET http://localhost:8081/
###
GET http://localhost:8081/health_check
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "a",
  "password": "a",
  "api_key": "db0fe35b-0d88-4d03-a774-12fbae54aa51"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "demo_mr",
  "password": "kia_demo_mr"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "demo_jb",
  "password": "kia_demo_jb"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "tester1",
  "password": "llars_tester1"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "tester2",
  "password": "llars_tester2"
}
###
POST http://backend-flask-service:8081/register
Content-Type: application/json

{
  "username": "tester3",
  "password": "llars_tester3"
}
###