GET http://localhost:8081/
###
GET http://localhost:8081/health_check
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "dev_user_1",
  "password": "zinumusu",
  "api_key": "e304823e-1d35-46ef-94cf-7c654d642dac"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "dev_user_2",
  "password": "locolore",
  "api_key": "db0fe35b-0d88-4d03-a774-12fbae54aa51"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "demo_mr",
  "password": "kia_demo_mr"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "demo_jb",
  "password": "kia_demo_jb"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "bke_dana",
  "password": "micivionterm"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "bke_maria",
  "password": "cernistinsto"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "tester2",
  "password": "llars_tester2"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "tester3",
  "password": "llars_tester3"
}
###
POST http://backend-flask-service:8081/auth/register_admin
Content-Type: application/json

{
  "username": "admin",
  "password": "llars_admin789",
  "api_key": "0b09e690-365b-4a55-b9b3-04c0614f773a",
  "admin_registration_key": "73525abb-3336-4553-8e54-751c9c1b965c"
}
###
POST http://backend-flask-service:8081/auth/register_admin
Content-Type: application/json

{
  "username": "admin2",
  "password": "llars_admin321",
  "api_key": "0db8a774-dbff-4361-930c-a47173f5ffce",
  "admin_registration_key": "73525abb-3336-4553-8e54-751c9c1b965c"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "ieb_vanessa",
  "password": "toralvamplech"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "ieb_franziska",
  "password": "kirchmasoosphie"
}
###
# POST https://llars.e-beratungsinstitut.de/api/register
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "ieb_michelle",
  "password": "ikasicherllea"
}
###
POST http://backend-flask-service:8081/auth/register
Content-Type: application/json

{
  "username": "steigerwald",
  "password": "neele",
  "api_key": "14fb4237-35c7-4ad4-9df1-002379a16d0e"
}