FROM node:23-bookworm
LABEL authors="philippsteigerwald"

WORKDIR /vue

COPY docker/vue/healthcheck.sh /usr/local/bin/healthcheck.sh
RUN mkdir /scripts
COPY docker/vue/start_vue.sh /scripts/start_vue.sh
COPY llars-frontend /vue/

RUN chmod +x /usr/local/bin/healthcheck.sh && \
   chmod +x /scripts/start_vue.sh

# Create non-root user and set permissions
RUN groupadd -r vueuser && useradd -r -g vueuser -u 1003 vueuser && \
    chown -R vueuser:vueuser /vue && \
    chown -R vueuser:vueuser /scripts

# Switch to non-root user
USER vueuser

EXPOSE 5173

CMD ["/scripts/start_vue.sh"]