FROM node:23-bookworm
LABEL authors="philippsteigerwald"

WORKDIR /vue

COPY docker/vue/healthcheck.sh /usr/local/bin/healthcheck.sh
RUN mkdir /scripts
COPY docker/vue/start_vue.sh /scripts/start_vue.sh
COPY llars-frontend /vue/

RUN chmod +x /usr/local/bin/healthcheck.sh && \
   chmod +x /scripts/start_vue.sh

EXPOSE 5173

CMD ["/scripts/start_vue.sh"]