# /docker/flask/Dockerfile-flask
# syntax=docker/dockerfile:1

# Verwenden eines offiziellen Python-Images als Basis
FROM public.ecr.aws/docker/library/python:3.10-slim
RUN apt-get -y update; apt-get -y install curl

# Setzt das Arbeitsverzeichnis im Container
WORKDIR /supervisor

# Installiert die notwendigen Python-Pakete aus der supervisor_requirements.txt
COPY /supervisor/ /supervisor/

# COPY ../tests/ /watchdog/tests/
COPY /docker/supervisor/supervisor_requirements.txt /supervisor/
COPY /docker/supervisor/start_supervisor.sh /supervisor/


RUN pip install --no-cache-dir -r /supervisor/supervisor_requirements.txt
# RUN chmod +x /tests/start_supervisor.sh
