"""
IJCAI 2026 demo seeder.

Builds ONE shared demo scenario per evaluation type (7 total), each with 20
items, owned by the system account ``ijcai_demo``, and a single configurable
referral link ``/join/ijcai`` that on signup enrols the visitor as ASSESSOR in
all 7 scenarios AND grants read-only manager VIEWER on all 7 (so conference
attendees can both evaluate and watch the live aggregated analysis).

Concept
-------
Shared scenarios (not per-user): everyone who scans the QR rates the SAME 20
items per type, so the Scenario-Manager analysis shows live inter-rater
reliability across all participants — the headline demo of a collaborative
evaluation platform.

Content
-------
Item content is shown in ENGLISH (best for the international IJCAI audience);
the German original is preserved in each item's metadata (``content_de`` /
per-turn ``de``). The evaluation CONFIG (task, dimensions, buckets, labels,
questions, options) is fully bilingual (de/en) and drives the UI chrome, which
switches with the user's language toggle. (To flip content to German, swap the
``en``/``de`` picks in ``_map_items`` — both languages are in the datasets.)

Datasets are generated by the ``ijcai-demo-data`` workflow into
``app/scripts/ijcai_demo/<type>.json`` (7 agents, one per type).

Showcase content beyond evaluation
----------------------------------
Evaluation alone shows only a third of LLARS, so the seeder additionally gives
``ijcai_demo`` two English prompt-engineering prompts ("Structured Situation
Analysis", "Empathic Reply Draft") and two COMPLETED batch-generation jobs
(10 counselling cases x 1 prompt x Mistral 24B + 128B = 20 outputs each). The
canned texts/metadata live in ``app/scripts/ijcai_demo/generation_seed.py``;
the cases are imported from ``db/seeders/demo_video_data.COUNSELLING_CASES``.

Every visitor gets their own editable COPY of the two prompts and read access
to the two jobs. That provisioning happens at registration time and is driven
by ``referral_links.provision_json``, which this seeder writes:

    {"clone_prompt_ids": [<UserPrompt.prompt_id>, ...],
     "share_job_ids":   [<GenerationJob.id>, ...]}

The link also confers the ``ijcai_reviewer`` role (prompt engineering +
generation + all evaluation types, no admin permissions). Visitors who joined
before this was in place are backfilled at the end of every seed run (role +
prompt clones + job shares) — see ``_backfill_demo_accounts``.

End of life
-----------
The demo has a defined end. This seeder sets the link's ``expires_at`` to
``LINK_EXPIRES_AT`` (2026-08-29 23:59:59 local) on every run, after which no NEW
registrations are possible. Existing conference accounts expire independently 7
days after their registration: ``scripts.demo_cleanup.expire_ijcai_accounts``
swaps all their roles for the empty ``demo_expired`` role and archives their
memberships — they can still log in, but nothing is usable any more.

Idempotent throughout: scenarios are matched by name + creator, prompts by
(owner, name), jobs by (name, creator), the referral link is updated in place,
and the backfill re-uses ``ReferralService.provision_demo_content`` which skips
what a user already has — safe to run after every deploy.

Usage:
    docker exec llars_flask_<color> python -m scripts.seed_ijcai_demo
    docker exec llars_flask_<color> python -m scripts.seed_ijcai_demo --reset
"""

import json
import logging
import os
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

OWNER_USERNAME = "ijcai_demo"
LINK_SLUG = "ijcai"
CAMPAIGN_NAME = "IJCAI 2026 Demo"
DATA_DIR = os.path.join(os.path.dirname(__file__), "ijcai_demo")

# Role conferred by the join link. Tailored for conference visitors: prompt
# engineering, batch generation, LLM view and all evaluation types — but no
# admin:* permissions and no referral/link management (unlike 'researcher').
LINK_ROLE_NAME = "ijcai_reviewer"

# End of life for the /join/ijcai link. IJCAI 2026 ends 2026-08-22; one week of
# grace covers late scans of a printed QR/flyer. Afterwards
# ReferralService.validate_link rejects the link, i.e. NO new registrations —
# accounts that already exist keep working until their own TTL kicks in
# (scripts.demo_cleanup.expire_ijcai_accounts, 7 days after registration).
#
# Naive LOCAL time on purpose: validate_link compares expires_at against
# datetime.now(), and every LLARS container runs TZ=Europe/Berlin
# (docker-compose.yml), so this is 2026-08-29 23:59:59 Europe/Berlin — the link
# survives the whole of 29 August.
#
# The seeder OVERWRITES this field on every run (config-as-code): the date is
# owned by this constant, not by the DB, so a manual DB edit is intentionally
# not sticky. Change the date here and re-run the seeder.
LINK_EXPIRES_AT = datetime(2026, 8, 29, 23, 59, 59)

# End of the evaluation window of the 7 demo scenarios. UTC on purpose — the
# scenario status computation compares against datetime.utcnow()
# (scenario_manager_api). Must stay AFTER the last possible account activity:
# link dies 2026-08-29 (local) + 7 days account TTL → 2026-09-05. A scenario
# whose end has passed is 'completed' and the EvaluationHub hides it from
# non-owners, so this date expiring early would blank the whole demo.
SCENARIO_END_AT = datetime(2026, 9, 5, 23, 59, 59)

# Prompt-engineering + batch-generation showcase owned by ijcai_demo. The names
# are the idempotency keys (prompts: owner+name, jobs: name+creator) and are
# also what the visitor sees, so they must stay stable across deploys.
PROMPT_ANALYSIS_NAME = "Structured Situation Analysis"
PROMPT_REPLY_NAME = "Empathic Reply Draft"
JOB_ANALYSIS_NAME = "Counselling Case Analysis — Mistral 24B vs 128B"
JOB_REPLY_NAME = "Empathic Reply Drafting — Mistral 24B vs 128B"

# Both models are public (no llm_model_permissions rows), so a visitor can
# re-run either job live with their own cloned prompt.
MODEL_24B_ID = "Global/Mistral/Mistral-Small-3.2-24B-Instruct-2506"
MODEL_128B_ID = "Global/Mistral/Mistral-Medium-3.5-128B"

# Asymmetric LLARS palette buckets/labels reuse the design-system colours.
_C = {"good": "#98d4bb", "mid": "#D1BC8A", "bad": "#e8a087",
      "a": "#88c4c8", "b": "#b0ca97", "c": "#D1BC8A", "d": "#e8a087", "e": "#88c4c8"}


def _L(de, en):
    return {"de": de, "en": en}


# --- per-type evaluation config (bilingual) ---------------------------------

_SCALE_1_5 = {
    "min": 1, "max": 5, "step": 1,
    "labels": {
        "1": _L("Sehr schlecht", "Very poor"),
        "2": _L("Schlecht", "Poor"),
        "3": _L("Mittel", "Fair"),
        "4": _L("Gut", "Good"),
        "5": _L("Sehr gut", "Very good"),
    },
}


# Per-type task ("Aufgabe") briefing, bilingual. Shown in the task pop-up/banner
# (resolveTaskMarkdown reads config.task_description_markdown).
_TASKS = {
    "rating": _L(
        "**Aufgabe:** Bewerten Sie die Beraterantwort auf den vier Likert-Skalen (Empathie, Klarheit, Hilfreichkeit, Angemessenheit) und vergeben Sie 1–5 Punkte pro Dimension.",
        "**Task:** Rate the counsellor's reply on the four Likert scales (empathy, clarity, helpfulness, appropriateness), 1–5 points per dimension."),
    "mail_rating": _L(
        "**Aufgabe:** Lesen Sie den E-Mail-Beratungsverlauf (Klient:in ↔ Berater:in) und bewerten Sie ihn auf den Skalen Empathie, Klarheit, Hilfreichkeit und Gesamteindruck.",
        "**Task:** Read the e-counselling exchange (client ↔ counsellor) and rate it on empathy, clarity, helpfulness and overall impression."),
    "ranking": _L(
        "**Aufgabe:** Lesen Sie die Nachricht der ratsuchenden Person und ordnen Sie die drei alternativen Beraterantworten in die Qualitäts-Buckets ein: **Gut**, **Mittel**, **Schwach**.",
        "**Task:** Read the help-seeker's message and sort the three alternative counsellor replies into the quality buckets: **Good**, **Moderate**, **Weak**."),
    "comparison": _L(
        "**Aufgabe:** Vergleichen Sie die beiden Beraterantworten **A** und **B** auf dieselbe Situation und wählen Sie die hilfreichere (oder Unentschieden).",
        "**Task:** Compare counsellor replies **A** and **B** to the same situation and pick the more helpful one (or a tie)."),
    "communication_comparison": _L(
        "**Aufgabe:** Lesen Sie den Gesprächsverlauf und entscheiden Sie, welche der beiden möglichen nächsten Beraterantworten Sie selbst senden würden.",
        "**Task:** Read the conversation and decide which of the two possible next counsellor replies you would send yourself."),
    "authenticity": _L(
        "**Aufgabe:** Entscheiden Sie, ob der Text von einem **Menschen** oder von einer **KI** geschrieben wurde.",
        "**Task:** Decide whether the text was written by a **human** or by an **AI**."),
    "labeling": _L(
        "**Aufgabe:** Wählen Sie die passende Themen-Kategorie für die Nachricht der ratsuchenden Person (Stress, Beziehung, Einsamkeit, Trauer oder Studium/Arbeit).",
        "**Task:** Choose the matching topic category for the help-seeker's message (stress, relationship, loneliness, grief, or study/work)."),
}


def _rating_config():
    return {"type": "rating", "config": {
        "task_description_markdown": _TASKS["rating"],
        "scale": _SCALE_1_5,
        "dimensions": [
            {"id": "empathy", "label": _L("Empathie", "Empathy"), "weight": 0.25},
            {"id": "clarity", "label": _L("Klarheit", "Clarity"), "weight": 0.25},
            {"id": "helpfulness", "label": _L("Hilfreichkeit", "Helpfulness"), "weight": 0.25},
            {"id": "appropriateness", "label": _L("Angemessenheit", "Appropriateness"), "weight": 0.25},
        ],
        "show_overall": True,
    }}


def _mail_rating_config():
    return {"type": "mail_rating", "config": {
        "task_description_markdown": _TASKS["mail_rating"],
        "scale": _SCALE_1_5,
        "dimensions": [
            {"id": "empathy", "label": _L("Empathie", "Empathy"), "weight": 0.3},
            {"id": "clarity", "label": _L("Klarheit", "Clarity"), "weight": 0.2},
            {"id": "helpfulness", "label": _L("Hilfreichkeit", "Helpfulness"), "weight": 0.3},
            {"id": "overall", "label": _L("Gesamteindruck", "Overall"), "weight": 0.2},
        ],
        "show_overall": True,
        "focus_role": "Berater",
    }}


def _ranking_config():
    return {"type": "ranking", "config": {
        "task_description_markdown": _TASKS["ranking"],
        "mode": "simple",
        "buckets": [
            {"id": "good", "label": _L("Gut", "Good"), "color": _C["good"], "order": 1},
            {"id": "mid", "label": _L("Mittel", "Moderate"), "color": _C["mid"], "order": 2},
            {"id": "bad", "label": _L("Schwach", "Weak"), "color": _C["bad"], "order": 3},
        ],
        "allow_ties": True,
        "require_complete": True,
    }}


def _comparison_config():
    # criteria_markdown (bilingual) wins over the flat German `criteria` list in
    # resolveCriteriaMarkdown — the flat list stays for schema compatibility
    # (Pydantic types it List[str], so it cannot carry translations itself);
    # without the markdown override the EN briefing leaked German criteria.
    return {"type": "comparison", "config": {
        "question": _L("Welche Beraterantwort ist besser?", "Which counsellor response is better?"),
        "criteria": ["Empathie", "Klarheit", "Hilfreichkeit"],
        "criteria_markdown": _L(
            "- Empathie\n- Klarheit\n- Hilfreichkeit",
            "- Empathy\n- Clarity\n- Helpfulness",
        ),
        "allow_tie": True,
        "show_source": False,
        "task_description_markdown": _TASKS["comparison"],
    }}


def _comm_comparison_config():
    return {"type": "communication_comparison", "config": {
        "question": _L("Welche Antwort würdest du senden?", "Which reply would you send?"),
        "response_prompt": _L("Wie würdest *du* hier antworten?", "How would *you* respond here?"),
        "criteria": ["Empathie", "Passung", "Klarheit"],
        # See _comparison_config for why this bilingual override exists.
        "criteria_markdown": _L(
            "- Empathie\n- Passung\n- Klarheit",
            "- Empathy\n- Fit\n- Clarity",
        ),
        "allow_tie": True,
        "show_source": False,
        "rater_note_enabled": True,
        "task_description_markdown": _TASKS["communication_comparison"],
    }}


def _authenticity_config():
    return {"type": "authenticity", "config": {
        "task_description_markdown": _TASKS["authenticity"],
        "options": [
            {"id": "human", "label": _L("Mensch", "Human")},
            {"id": "ai", "label": _L("KI-generiert", "AI-generated")},
        ],
        "show_confidence": True,
    }}


_LABEL_CATS = [
    ("stress", _L("Stress / Überforderung", "Stress / overwhelm"), _C["a"]),
    ("relationship", _L("Beziehung / Konflikt", "Relationship / conflict"), _C["b"]),
    ("loneliness", _L("Einsamkeit", "Loneliness"), _C["c"]),
    ("grief", _L("Trauer / Verlust", "Grief / loss"), _C["d"]),
    ("study_work", _L("Studium / Arbeit", "Study / work"), _C["e"]),
]


def _labeling_config():
    return {"type": "labeling", "config": {
        "mode": "single",
        "labels": [{"id": cid, "label": lbl, "color": col} for cid, lbl, col in _LABEL_CATS],
        "allow_other": False,
    }}


# Registry: type -> (scenario display name, config builder, item mapper key)
TYPES = [
    ("rating", _L("IJCAI Demo: Rating", "IJCAI Demo: Rating"), _rating_config),
    ("ranking", _L("IJCAI Demo: Ranking", "IJCAI Demo: Ranking"), _ranking_config),
    ("mail_rating", _L("IJCAI Demo: Mail-Bewertung", "IJCAI Demo: Mail Rating"), _mail_rating_config),
    ("comparison", _L("IJCAI Demo: Vergleich", "IJCAI Demo: Comparison"), _comparison_config),
    ("communication_comparison", _L("IJCAI Demo: Kommunikationsvergleich", "IJCAI Demo: Communication Comparison"), _comm_comparison_config),
    ("authenticity", _L("IJCAI Demo: Echtheit", "IJCAI Demo: Authenticity"), _authenticity_config),
    ("labeling", _L("IJCAI Demo: Labeling", "IJCAI Demo: Labeling"), _labeling_config),
]


# --- item mapping (dataset -> NativeItem dicts) -----------------------------

def _conv_content(raw, lang="en"):
    """ConversationContent dict from a dataset 'conversation' list. ``lang`` picks
    the shown turn language (the other is preserved per-turn under metadata)."""
    other = "de" if lang == "en" else "en"
    return {
        "type": "conversation",
        "messages": [
            {"role": m.get("role", "Klient"),
             "content": m.get(lang) or m.get("en") or m.get("de", ""),
             "metadata": {other: m.get(other, "")}}
            for m in raw
        ],
    }


def _features_from_candidates(cands):
    """NativeFeature dicts (A, B, ...) from dataset candidates (English content)."""
    feats = []
    for idx, c in enumerate(cands):
        feats.append({
            "type": "candidate",
            "content": c.get("en") or c.get("de", ""),
            "generated_by": c.get("generated_by") or c.get("source") or "unknown",
        })
    return feats


def _map_items(eval_type, items, lang="en"):
    """Map a dataset's items to LLARS-Native item dicts for create_scenario_one_shot.

    ``lang`` (en|de) picks the visible item/label/conversation language; the
    other language is preserved in metadata. Default 'en' keeps IJCAI behaviour.
    """
    other = "de" if lang == "en" else "en"
    out = []
    for i, it in enumerate(items, start=1):
        nid = f"{eval_type}_{i}"
        label = it.get(f"label_{lang}") or it.get("label_en") or it.get("label_de") or f"Item {i}"
        meta = {f"content_{other}": it.get(f"content_{other}", ""),
                f"label_{other}": it.get(f"label_{other}", "")}
        if it.get("ground_truth"):
            meta["ground_truth"] = it["ground_truth"]

        if eval_type in ("mail_rating", "communication_comparison"):
            content = _conv_content(it.get("conversation", []), lang)
        else:
            content = it.get(f"content_{lang}", "") or it.get("content_en", "") or it.get("content_de", "") or label

        # source: for AUTHENTICITY the rater must NOT see whether the text is
        # human- or AI-written — that's exactly what they guess. So the visible
        # source is neutral ('unknown', no name) and the gold (source_type +
        # generator) is kept ONLY in metadata for scoring/analysis. For all other
        # types the source is the (human) client text.
        if eval_type == "authenticity":
            stype, sname = "unknown", None
            meta["ground_truth"] = it.get("source_type")          # gold: human|llm
            meta["source_name"] = it.get("source_name")           # gold generator
        else:
            stype, sname = "human", None

        item = {
            "id": nid,
            "label": label,
            "source": {"type": stype, "name": sname},
            "content": content,
            "metadata": meta,
            "features": [],
        }
        if eval_type in ("comparison", "communication_comparison", "ranking"):
            item["features"] = _features_from_candidates(it.get("candidates", []))
        out.append(item)
    return out


# --- seeding ----------------------------------------------------------------

def _ensure_owner(db):
    from db.models import User
    user = User.query.filter_by(username=OWNER_USERNAME).first()
    if user:
        return user
    user = User(username=OWNER_USERNAME, group_id=1)
    # password_hash may be required/non-null depending on schema; set a random unusable one.
    if hasattr(user, "password_hash"):
        import secrets
        user.password_hash = secrets.token_urlsafe(24)
    db.session.add(user)
    db.session.flush()
    logger.info("Created owner user %s", OWNER_USERNAME)
    return user


def _load_dataset(eval_type):
    path = os.path.join(DATA_DIR, f"{eval_type}.json")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)["items"]


def _inject_task(config_json: dict, eval_type: str) -> None:
    """Write the per-type task ('Aufgabe') text where resolveTaskMarkdown reads it.

    Pydantic strips an unknown task_description_markdown from non-comparison
    configs, so we set it at the TOP LEVEL (root.task_description_markdown — a
    resolveTaskMarkdown fallback path) and mirror it into config /
    eval_config.config, covering every read path for every type.
    """
    task = _TASKS.get(eval_type)
    if not task:
        return
    config_json['task_description_markdown'] = task
    if isinstance(config_json.get('config'), dict):
        config_json['config']['task_description_markdown'] = task
    ec = config_json.get('eval_config')
    if isinstance(ec, dict) and isinstance(ec.get('config'), dict):
        ec['config']['task_description_markdown'] = task


# --- prompt engineering showcase --------------------------------------------
#
# Block structure mirrors demo_video_service._build_preseed_prompt_content:
# {"blocks": {<block name>: {"content", "position", "author"}}}. The Prompt
# Engineering UI renders the blocks in ``position`` order and concatenates
# System Prompt + Task Explanation into the system message, while the Data
# Format Explanation block carries the {{subject}} / {{content}} variables that
# batch generation substitutes per source item.

def _build_analysis_prompt_content():
    """Prompt 1: five-section situation analysis of an e-counselling thread.

    Deliberately prescriptive (fixed section names, quotes as evidence, no
    speculation) so that outputs of different models are directly comparable —
    that comparison is what the conference demo is about. The Situation section
    reuses the proven numbered-list-with-quotes wording of the demo-video
    prompt; the four analytical sections are what make the result usable in a
    counselling context.
    """
    return {
        "blocks": {
            "System Prompt": {
                "content": (
                    "You are an analytical assistant for professionals in psychosocial online "
                    "counselling. You read email exchanges between help-seeking clients and "
                    "counsellors and turn them into a structured, factual case analysis that a "
                    "counsellor can act on. You never diagnose, and you never invent information "
                    "that is not in the thread."
                ),
                "position": 0,
                "author": OWNER_USERNAME,
            },
            "Task Explanation": {
                "content": (
                    "Analyse the email thread and return exactly these five sections, in this "
                    "order, each with its heading in bold:\n\n"
                    "**Situation** — up to three numbered points describing the client's current "
                    "life circumstances. Each point: at most two sentences, followed by direct "
                    "quotes from the thread as evidence, placed after a dash. Cover housing, "
                    "family relationships, children (age, development, health), work or "
                    "education, health, and social conflicts where the thread mentions them.\n"
                    "**Emotional State** — how the client and any children involved are doing "
                    "emotionally, grounded in what they say and do, not in assumptions.\n"
                    "**Needs** — three to five bullet points, the most urgent first.\n"
                    "**Risk Assessment** — one of Low / Moderate / Elevated, followed by the "
                    "concrete indicators and any protective factors. Name explicitly when the "
                    "thread contains no indication of danger.\n"
                    "**Suggested Approach** — two to four numbered, concrete next steps for the "
                    "counsellor.\n\n"
                    "Rules:\n"
                    "- Use only facts from the thread; mark nothing as certain that is not stated\n"
                    "- No diagnoses, no medical or legal advice\n"
                    "- No introductory or closing phrases — start with the first heading\n"
                    "- When counselling parents, always include the children's situation"
                ),
                "position": 1,
                "author": OWNER_USERNAME,
            },
            "Data Format Explanation": {
                "content": (
                    "Subject: {{subject}}\n\n"
                    "Email thread:\n"
                    "{{content}}\n\n"
                    "The thread is given in chronological order, alternating between the client "
                    "and the counsellor. Return only the five sections."
                ),
                "position": 2,
                "author": OWNER_USERNAME,
            },
        }
    }


def _build_reply_prompt_content():
    """Prompt 2: draft a supportive counsellor reply to the client's last message.

    Complements prompt 1 on the SAME cases: analysis vs. generation on identical
    input is the contrast visitors compare in the batch-generation results view.
    The constraints (length, one open question, no diagnoses) keep the drafts
    comparable across models and safe to show at a public booth.
    """
    return {
        "blocks": {
            "System Prompt": {
                "content": (
                    "You are an experienced counsellor in psychosocial online counselling. You "
                    "write warm, respectful replies to help-seeking clients: plain language, no "
                    "jargon, no false reassurance. You take what the client says seriously and "
                    "you never diagnose or give medical or legal advice."
                ),
                "position": 0,
                "author": OWNER_USERNAME,
            },
            "Task Explanation": {
                "content": (
                    "Draft the counsellor's reply to the client's LATEST message in the thread.\n\n"
                    "The reply must:\n"
                    "- open by acknowledging and validating what the client feels, without "
                    "platitudes\n"
                    "- refer to at least two concrete details from the latest message, so the "
                    "client can tell they were read\n"
                    "- offer one or two practical, realistic next steps the client could take in "
                    "the coming days\n"
                    "- end with exactly one open question that invites the client to write back\n\n"
                    "Rules:\n"
                    "- roughly 150 to 250 words, written directly to the client in the second person\n"
                    "- no diagnoses, no medical or legal advice; signpost to appropriate services "
                    "instead\n"
                    "- do not promise outcomes, and do not minimise the situation\n"
                    "- return only the reply text, with no salutation line and no signature"
                ),
                "position": 1,
                "author": OWNER_USERNAME,
            },
            "Data Format Explanation": {
                "content": (
                    "Subject: {{subject}}\n\n"
                    "Email thread:\n"
                    "{{content}}\n\n"
                    "The thread is given in chronological order, alternating between the client "
                    "and the counsellor. The last client message is the one you reply to."
                ),
                "position": 2,
                "author": OWNER_USERNAME,
            },
        }
    }


def _get_block(content: dict, name: str) -> str:
    """Text of a named prompt block ('' when the block is missing)."""
    block = (content or {}).get("blocks", {}).get(name, {})
    return block.get("content", "") if isinstance(block, dict) else ""


def _render_system(content: dict) -> str:
    """System message a generation run would build from a prompt's blocks."""
    parts = [_get_block(content, "System Prompt"), _get_block(content, "Task Explanation")]
    return "\n\n".join(p for p in parts if p)


def _render_user(content: dict, case: dict) -> str:
    """User message for one source item ({{subject}}/{{content}} substituted)."""
    tpl = _get_block(content, "Data Format Explanation")
    if not tpl:
        return f"Subject: {case['subject']}\n\n{case['content']}"
    return tpl.replace("{{subject}}", case["subject"]).replace("{{content}}", case["content"])


def _seed_prompts(db, owner) -> tuple:
    """Create/refresh the two showcase prompts owned by ``ijcai_demo``.

    Idempotent by (user_id, name): an existing prompt is reused, and its content
    is overwritten when the template here has changed — otherwise a deploy that
    improves the wording would leave the demo account on the old version while
    new visitors get clones of it.

    Returns ``(prompts_by_name, actions)``.
    """
    from db.models import UserPrompt

    templates = [
        (PROMPT_ANALYSIS_NAME, _build_analysis_prompt_content()),
        (PROMPT_REPLY_NAME, _build_reply_prompt_content()),
    ]

    prompts, actions = {}, []
    for name, content in templates:
        prompt = UserPrompt.query.filter_by(user_id=owner.id, name=name).first()
        if not prompt:
            prompt = UserPrompt(user_id=owner.id, name=name, content=content)
            db.session.add(prompt)
            db.session.flush()
            actions.append(f"Created prompt '{name}' (id={prompt.prompt_id})")
        elif (prompt.content or {}) != content:
            prompt.content = content
            actions.append(f"Updated prompt '{name}' (id={prompt.prompt_id}) to current template")
        else:
            actions.append(f"Prompt '{name}' already up to date (id={prompt.prompt_id})")
        prompts[name] = prompt

    db.session.commit()
    return prompts, actions


def _seed_generation_jobs(db, prompts: dict) -> tuple:
    """Create the two COMPLETED batch-generation jobs owned by ``ijcai_demo``.

    Each job is a 10 cases x 1 prompt x 2 models matrix (20 outputs) with canned
    content — deterministic and independent of any live LLM key, so re-seeding
    after a deploy never costs tokens or fails on a rotated key. Idempotent by
    (name, created_by): an existing job is left untouched (like the demo-video
    seeder), because rebuilding it would orphan the shares handed to visitors.

    Returns ``(job_ids, actions)``; ``job_ids`` is empty when a required model
    is missing (seeding is skipped gracefully in that case).
    """
    from db.models.generation import (
        GeneratedOutput, GeneratedOutputStatus, GenerationJob, GenerationJobStatus,
    )
    from db.models.llm_model import LLMModel
    from db.seeders.demo_video_data import COUNSELLING_CASES
    from scripts.ijcai_demo.generation_seed import (
        MODEL_128B, MODEL_24B, PROMPT_ANALYSIS, PROMPT_REPLY,
        OUTPUT_METADATA, build_sample_outputs, job_totals,
    )

    actions = []
    model_24b = LLMModel.query.filter_by(model_id=MODEL_24B_ID).first()
    model_128b = LLMModel.query.filter_by(model_id=MODEL_128B_ID).first()
    if not model_24b or not model_128b:
        missing = [mid for mid, m in ((MODEL_24B_ID, model_24b), (MODEL_128B_ID, model_128b)) if not m]
        logger.warning("LLM model(s) %s not found — skipping generation job seeding", missing)
        actions.append(f"Skipped generation jobs: LLM model(s) not found ({', '.join(missing)})")
        return [], actions

    sample_outputs = build_sample_outputs()
    models = [(model_24b, MODEL_24B), (model_128b, MODEL_128B)]
    now = datetime.utcnow()

    specs = [
        (JOB_ANALYSIS_NAME, PROMPT_ANALYSIS_NAME, PROMPT_ANALYSIS,
         "IJCAI 2026 demo batch: structured five-section case analysis of 10 English "
         "counselling threads, generated with Mistral Small 24B and Mistral Medium 128B."),
        (JOB_REPLY_NAME, PROMPT_REPLY_NAME, PROMPT_REPLY,
         "IJCAI 2026 demo batch: empathic counsellor reply drafts for the same 10 English "
         "counselling threads, generated with Mistral Small 24B and Mistral Medium 128B."),
    ]

    job_ids = []
    for job_name, prompt_name, prompt_key, description in specs:
        existing = GenerationJob.query.filter_by(name=job_name, created_by=OWNER_USERNAME).first()
        if existing:
            job_ids.append(existing.id)
            actions.append(f"Job '{job_name}' already exists (id={existing.id})")
            continue

        prompt_content = prompts[prompt_name].content or {}
        totals = job_totals(prompt_key)
        total_outputs = len(COUNSELLING_CASES) * len(models)

        # Timestamps sit in the past so the job reads as a finished run rather
        # than as something that is still going (the UI shows relative times).
        job = GenerationJob(
            name=job_name,
            description=description,
            status=GenerationJobStatus.COMPLETED,
            config_json={
                "mode": "matrix",
                "sources": {"type": "manual", "items": COUNSELLING_CASES},
                "prompts": [{"template_name": prompt_name}],
                "llm_models": [model_24b.model_id, model_128b.model_id],
                "generation_params": {"temperature": 0.7, "max_tokens": 700},
            },
            total_items=total_outputs,
            completed_items=total_outputs,
            failed_items=0,
            total_tokens=totals["total_tokens"],
            total_cost_usd=totals["total_cost_usd"],
            created_by=OWNER_USERNAME,
            created_at=now - timedelta(days=1, hours=3),
            started_at=now - timedelta(days=1, hours=3),
            completed_at=now - timedelta(days=1, hours=2, minutes=48),
        )
        db.session.add(job)
        db.session.flush()

        rendered_system = _render_system(prompt_content)
        output_idx = 0
        for case_idx, case in enumerate(COUNSELLING_CASES):
            rendered_user = _render_user(prompt_content, case)
            for model, model_key in models:
                meta = OUTPUT_METADATA[prompt_key][model_key][case_idx]
                db.session.add(GeneratedOutput(
                    job_id=job.id,
                    llm_model_id=model.id,
                    llm_model_name=model.model_id,
                    prompt_variant_name=prompt_name,
                    # source_index is how the results view groups outputs by case.
                    prompt_variables_json={
                        "source_index": case_idx,
                        "source_subject": case["subject"],
                    },
                    generated_content=sample_outputs[prompt_key][model_key][case_idx],
                    rendered_system_prompt=rendered_system,
                    rendered_user_prompt=rendered_user,
                    status=GeneratedOutputStatus.COMPLETED,
                    input_tokens=meta["input_tokens"],
                    output_tokens=meta["output_tokens"],
                    total_cost_usd=meta["cost_usd"],
                    processing_time_ms=meta["processing_time_ms"],
                    attempt_count=1,
                    created_at=now - timedelta(days=1, hours=3),
                    completed_at=now - timedelta(days=1, hours=3) + timedelta(seconds=30 * output_idx),
                ))
                output_idx += 1

        db.session.commit()
        job_ids.append(job.id)
        actions.append(f"Created job '{job_name}' (id={job.id}) with {total_outputs} outputs")

    return job_ids, actions


def _backfill_demo_accounts(db, link) -> list:
    """Give already-registered visitors the role and content the link now grants.

    The link originally handed out the 'evaluator' role and no prompts/jobs, so
    accounts created before this seeder version would silently keep the smaller
    demo. Candidates are the deterministic demo usernames of this link
    (``demo-<slug>-*``, see referral_routes._demo_username_from_email) plus every
    username recorded in referral_registrations for this link — the latter also
    covers existing users who redeemed the code instead of registering.

    Provisioning itself is delegated to ReferralService.provision_demo_content
    (same code path as a live registration, idempotent). That method is added by
    the referral-provisioning work; while it is not deployed yet the backfill
    logs a warning and only fixes the roles, so the seeder never crashes.
    """
    from db.models import User
    from db.models.referral import ReferralRegistration
    from services.permission_service import PermissionService
    from services.referral_service import ReferralService

    usernames = {
        row.username for row in
        ReferralRegistration.query.filter_by(link_id=link.id).all()
    }
    usernames.update(
        u.username for u in
        User.query.filter(User.username.like(f"demo-{LINK_SLUG}-%")).all()
    )
    usernames.discard(OWNER_USERNAME)
    if not usernames:
        return []

    can_provision = hasattr(ReferralService, "provision_demo_content")
    if not can_provision:
        logger.warning(
            "ReferralService.provision_demo_content is missing — backfilling roles only. "
            "Re-run this seeder after the referral provisioning is deployed."
        )

    checked, roles_assigned, roles_unresolved, provisioned, failed = 0, 0, 0, 0, 0
    prompts_cloned, jobs_shared = 0, 0
    for username in sorted(usernames):
        user = User.query.filter_by(username=username).first()
        if not user:
            continue  # registration row without an account (deleted user)
        checked += 1
        try:
            # assign_role is idempotent (returns True when the row already
            # exists) and returns False when the role itself is unknown.
            if PermissionService.assign_role(
                username=username,
                role_name=LINK_ROLE_NAME,
                admin_username="ijcai_demo_seeder",
            ):
                roles_assigned += 1
            else:
                roles_unresolved += 1
            if can_provision:
                # Never raises and commits itself; returns a per-user summary.
                summary = ReferralService.provision_demo_content(user, link) or {}
                prompts_cloned += summary.get("prompts_cloned", 0)
                jobs_shared += summary.get("jobs_shared", 0)
                provisioned += 1
        except Exception as exc:
            # One broken account must not abort the backfill for the others.
            db.session.rollback()
            failed += 1
            logger.warning("Backfill failed for %s: %s", username, exc)

    if roles_unresolved:
        logger.warning(
            "Role '%s' could not be assigned to %d account(s) — does the role exist?",
            LINK_ROLE_NAME, roles_unresolved,
        )

    actions = [
        f"Backfill: {checked} existing demo account(s) checked "
        f"({len(usernames)} candidate username(s)), "
        f"role '{LINK_ROLE_NAME}' ensured for {roles_assigned}"
    ]
    if roles_unresolved:
        actions.append(f"Backfill: role '{LINK_ROLE_NAME}' unresolved for {roles_unresolved} account(s)")
    if can_provision:
        actions.append(
            f"Backfill: provisioning applied to {provisioned} account(s) — "
            f"{prompts_cloned} prompt clone(s), {jobs_shared} job share(s) created"
        )
    else:
        actions.append("Backfill: provisioning skipped (ReferralService.provision_demo_content missing)")
    if failed:
        actions.append(f"Backfill: {failed} account(s) failed (see log)")
    return actions


# --- entrypoint -------------------------------------------------------------

def seed_ijcai_demo(reset: bool = False) -> dict:
    from db import db
    from db.models import RatingScenarios, ReferralCampaign
    from db.models.referral import ReferralLink
    from schemas.api_v1.scenario_api import ScenarioCreateRequest
    from services.api_v1_scenario_service import create_scenario_one_shot, _build_config_json

    owner = _ensure_owner(db)
    db.session.commit()

    begin = datetime.utcnow()
    # Fixed end date instead of the old "begin + 8 weeks": the relative window
    # silently expired on 2026-08-02 (seeded 2026-06-07) and an ended scenario
    # is status 'completed' — which the EvaluationHub HIDES from non-owners
    # (scenario_manager_api status computation, utcnow-based), i.e. conference
    # visitors would have seen NOTHING. Config-as-code like LINK_EXPIRES_AT:
    # refreshed on every seed run, also on the reuse path below.
    end = SCENARIO_END_AT
    scenario_ids = []
    actions = []

    for eval_type, name, cfg_builder in TYPES:
        display_name = name["en"]
        items = _map_items(eval_type, _load_dataset(eval_type))
        payload = ScenarioCreateRequest(
            name=display_name,
            description=("IJCAI 2026 live demo — " + name["de"]),
            eval_config=cfg_builder(),
            items={"items": items},
            assessors=[],  # participants join via the referral link, not pre-assigned
            begin=begin,
            end=end,
        )

        existing = (RatingScenarios.query
                    .filter_by(scenario_name=display_name, created_by=OWNER_USERNAME)
                    .first())
        if existing and reset:
            # Deep delete via the shared service — a bare session.delete() dies
            # on the cascade-less per-item evaluation relationships (NOT NULL
            # scenario_id → IntegrityError, seen on prod 2026-08-16) and would
            # leave the scenario's EvaluationItems behind as orphans that the
            # import service re-uses by chat_id, resurrecting stale content on
            # the re-seed right below.
            from services.scenario_deletion_service import delete_scenario_deep
            delete_scenario_deep(existing)
            db.session.commit()
            existing = None

        if existing:
            # Re-runnable: refresh the config (task texts, dimensions, labels,
            # buckets, …) on the existing scenario WITHOUT recreating it — keeps
            # the scenario id, its items, and the referral link intact. Items are
            # not re-imported (only config changes are picked up on re-run).
            cj = _build_config_json(payload)
            _inject_task(cj, eval_type)
            existing.config_json = cj
            # Refresh the evaluation window too (config-as-code): the original
            # relative end date expired mid-August and made every scenario
            # 'completed' → hidden from visitors. See SCENARIO_END_AT.
            existing.end = SCENARIO_END_AT
            if existing.begin and existing.begin > datetime.utcnow():
                existing.begin = begin  # never leave a scenario in 'draft'
            db.session.add(existing)
            db.session.commit()
            scenario_ids.append(existing.id)
            logger.info("Scenario '%s' (id=%s) — config refreshed", display_name, existing.id)
            continue

        scenario = create_scenario_one_shot(payload, OWNER_USERNAME)
        # Overlay the top-level task text (Pydantic strips task_description_markdown
        # from non-comparison configs; resolveTaskMarkdown also reads it at root).
        cj = dict(scenario.config_json or {})
        _inject_task(cj, eval_type)
        scenario.config_json = cj
        db.session.add(scenario)
        db.session.commit()
        scenario_ids.append(scenario.id)
        logger.info("Created scenario '%s' (id=%s, %d items)", display_name, scenario.id, len(items))

    # Prompt-engineering + batch-generation showcase owned by ijcai_demo. Seeded
    # BEFORE the link, because the link's provision_json references their ids.
    prompts, prompt_actions = _seed_prompts(db, owner)
    actions.extend(prompt_actions)
    for line in prompt_actions:
        logger.info(line)

    job_ids, job_actions = _seed_generation_jobs(db, prompts)
    actions.extend(job_actions)
    for line in job_actions:
        logger.info(line)

    # Referral link: enrol into all 7 as assessor + viewer, configurable signup.
    campaign = ReferralCampaign.query.filter_by(name=CAMPAIGN_NAME).first()
    if not campaign:
        campaign = ReferralCampaign(name=CAMPAIGN_NAME, status="active", created_by=OWNER_USERNAME)
        db.session.add(campaign)
        db.session.flush()

    link = ReferralLink.query.filter_by(slug=LINK_SLUG).first()
    if not link:
        link = ReferralLink(campaign_id=campaign.id, slug=LINK_SLUG, created_by=OWNER_USERNAME)
        db.session.add(link)
    link.campaign_id = campaign.id
    # ijcai_reviewer instead of evaluator: conference visitors also need prompt
    # engineering and batch generation, but must NOT get the extra powers of
    # 'researcher' (referral link creation, anonymisation). The registration
    # route re-checks this against ALLOWED_REFERRAL_ROLES and falls back to
    # 'evaluator' if the role is not allowlisted there.
    link.role_name = LINK_ROLE_NAME
    link.label = "IJCAI 2026 Demo"
    link.is_active = True
    # Hard end of life for NEW sign-ups — see LINK_EXPIRES_AT.
    link.expires_at = LINK_EXPIRES_AT
    link.target_scenario_ids = scenario_ids
    link.viewer_scenario_ids = scenario_ids
    link.signup_mode = "email"   # conference default: QR -> email -> in
    link.default_locale = "en"   # IJCAI demo is English by default (join + profile)
    link.collect_email = True
    link.collect_email_optional = False
    link.collect_display_name = True

    # Per-registration provisioning: every visitor gets an editable CLONE of the
    # two prompts and a SHARE on the two jobs (cloning 40 output rows per visitor
    # would be wasteful, and the shared results are what makes live IRR-style
    # comparison possible). Contract: {"clone_prompt_ids": [...],
    # "share_job_ids": [...]} — consumed by ReferralService.provision_demo_content.
    provision = {
        "clone_prompt_ids": [prompts[n].prompt_id for n in (PROMPT_ANALYSIS_NAME, PROMPT_REPLY_NAME)],
        "share_job_ids": job_ids,
    }
    if hasattr(link, "provision_json"):
        link.provision_json = json.dumps(provision)
        actions.append(f"Link provisioning set: {provision}")
    else:
        # Column not deployed yet — never fail the seed run over it.
        logger.warning(
            "ReferralLink.provision_json is missing — prompt/job provisioning NOT stored. "
            "Re-run this seeder after the referral provisioning migration is deployed."
        )
        actions.append("Link provisioning skipped (ReferralLink.provision_json missing)")
    db.session.commit()

    # Visitors who joined before the role/provisioning existed get the same
    # content retroactively (idempotent — see _backfill_demo_accounts).
    backfill_actions = _backfill_demo_accounts(db, link)
    actions.extend(backfill_actions)
    for line in backfill_actions:
        logger.info(line)

    result = {
        "scenario_ids": scenario_ids,
        "prompt_ids": provision["clone_prompt_ids"],
        "job_ids": job_ids,
        "link_slug": LINK_SLUG,
        "link_code": link.code,
        "link_role": link.role_name,
        "join_url": f"/join/{link.slug or link.code}",
        "signup_mode": link.signup_mode,
        "link_expires_at": link.expires_at.isoformat() if link.expires_at else None,
        "actions": actions,
    }
    logger.info("IJCAI demo seeded: %s", result)
    return result


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    # main.py builds the Flask app at module level (no factory); import it.
    from main import app
    logging.basicConfig(level=logging.INFO)
    with app.app_context():
        res = seed_ijcai_demo(reset="--reset" in sys.argv)
        print("\nResult:", json.dumps(res, indent=2, ensure_ascii=False))
